### ISSUE TITLE
Fatal error: DeliveryDate required in the request

### ISSUE THREAD

**Issue by gsdkkr** [thirtybees/postnl-api-php#99]
It seems like "DeliveryDate" is not being passed into the request, event when provided.

When attempting to use the `getSentDate` method, I keep getting the following exception (error is further down in it's entirety):
```
Fatal error: Uncaught Firstred\PostNL\Exception\CifException: 
DeliveryDate required in the request (DeliveryDate required in the request) in 
C:\...\vendor\firstred\postnl-api-php\src\Service\ResponseProcessor\Rest\AbstractRestResponseProcessor.php:122
...
```

I have tried different pieces of code, even code from the documentation. Here are some examples:
```php
$sentDate = $postnl->getSentDate(
    (new GetSentDateRequest())
        ->setGetSentDate(
            (new GetSentDate())
                ->setAllowSundaySorting(false)
                ->setCountryCode('NL')
                ->setHouseNr('66')
                ->setOptions(['Morning', 'Daytime'])
                ->setPostalCode('2132WT')
                ->setDeliveryDate(date('d-m-Y H:i:s'))
                ->setShippingDuration('1')
        )
);

$sentDate = $postnl->getSentDate(
    (new GetSentDateRequest())
        ->setGetSentDate(
            (new GetSentDate())
                ->setAllowSundaySorting($allowSundaySorting)
                ->setCountryCode($countryCode)
                ->setOptions($options)
                ->setPostalCode($postalCode)
                ->setDeliveryDate($deliveryDate) // This is a DateTimeInterface
                ->setShippingDuration($shippingDuration)
        )
);
```
Each of them returning the same exact error:

```
Fatal error: Uncaught Firstred\PostNL\Exception\CifException: DeliveryDate required in the request (DeliveryDate required in the request) in C:\...\vendor\firstred\postnl-api-php\src\Service\ResponseProcessor\Rest\AbstractRestResponseProcessor.php:122 
Stack trace: 
	#0 C:\...\vendor\firstred\postnl-api-php\src\Service\ResponseProcessor\Rest\DeliveryDateServiceRestResponseProcessor.php(95): Firstred\PostNL\Service\ResponseProcessor\Rest\AbstractRestResponseProcessor->validateResponse(Object(GuzzleHttp\Psr7\Response)) 
	#1 C:\...\vendor\firstred\postnl-api-php\src\Service\DeliveryDateService.php(183): Firstred\PostNL\Service\ResponseProcessor\Rest\DeliveryDateServiceRestResponseProcessor->processGetSentDateResponse(Object(GuzzleHttp\Psr7\Response)) 
	#2 C:\...\vendor\firstred\postnl-api-php\src\PostNL.php(2041): Firstred\PostNL\Service\DeliveryDateService->getSentDate(Object(Firstred\PostNL\Entity\Request\GetSentDateRequest)) 
	#3 C:\...\core\Helpers\PostNLHelper.php(119): Firstred\PostNL\PostNL->getSentDate(Object(Firstred\PostNL\Entity\Request\GetSentDateRequest)) 
	#4 C:\...\core\Controllers\DebugController.php(129): WWP\WebShop\Helpers\PostNLHelper->getSentDate(Object(DateTimeImmutable), '1234AB', '1', 'NL') 
	#5 [internal function]: WWP\WebShop\Controllers\DebugController->testPostNl(Object(WWP\WebShop\Helpers\PostNLHelper)) 
	#6 {main} thrown in C:\...\vendor\firstred\postnl-api-php\src\Service\ResponseProcessor\Rest\AbstractRestResponseProcessor.php on line 122
```

So eventhough the DeliveryDate is given, it still throws this error.

**Comment by firstred** [comment]
Fixed by #100

Thanks for the PR!
